tap "bios-marcel/cordless"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "mongodb/brew"
tap "rhysd/actionlint", "https://github.com/rhysd/actionlint"
tap "rhysd/tweet-app", "https://github.com/rhysd/tweet-app"
tap "tlk/imagemagick-x11"
tap "yudai/gotty"
tap "zegervdv/zathura"

# Core application library for C
brew "glib"

# Interpreted, interactive, object-oriented programming language
brew "python@3.9"

# Generate introspection data for GObject libraries
brew "gobject-introspection"

# OpenType text shaping engine
brew "harfbuzz"

# Framework for layout and rendering of i18n text
brew "pango"

# Icons for the GNOME project
brew "adwaita-icon-theme"

# Interpreted, interactive, object-oriented programming language
brew "python@3.10"

# Record and share terminal sessions
brew "asciinema"

# Microsoft Azure CLI 2.0
brew "azure-cli"

# Bourne-Again SHell, a UNIX command interpreter
brew "bash"

# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"

# Decentralized, peer to peer payment network
brew "bitcoin"

# Glorious Glasgow Haskell Compilation System
brew "ghc"

# Command-line interface for Cabal and Hackage
brew "cabal-install"

# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"

# Cross-platform make
brew "cmake"

# C implementation of Markdown
brew "discount"

# Create Docker hosts locally and on cloud providers
brew "docker-machine"

# More intuitive version of du in rust
brew "dust"

# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"

# Validating, recursive, caching DNS resolver
brew "unbound"

# GNU Emacs text editor
brew "emacs"

# Calculator REPL, similar to bc(1)
brew "eva"

# Simple, fast and user-friendly alternative to find
brew "fd"

# Banner-like program prints strings as ASCII art
brew "figlet"

# Command-line fuzzy finder written in Go
brew "fzf"

# GNU awk utility
brew "gawk"

# GNU compiler collection
brew "gcc"

# GNU debugger
brew "gdb"

# GitHub command-line tool
brew "gh"

# Syntax-highlighting pager for git and diff output
brew "git-delta"

# Powerful, lightweight programming language
brew "lua"

# Command-driven, interactive function plotting
brew "gnuplot"

# Open source programming language to build simple/reliable/efficient software
brew "go"

# Fast linters runner for Go
brew "golangci-lint"

# Language server for the Go language
brew "gopls"

# Graph visualization software from AT&T and Bell Labs
brew "graphviz"

# GSettings schemas for desktop components
brew "gsettings-desktop-schemas"

# Command-line hex viewer
brew "hexyl"

# Haskell source code suggestions
brew "hlint"

# Improved top (interactive process viewer)
brew "htop"

# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"

# Configurable static site generator
brew "hugo"

# Lightweight and flexible command-line JSON processor
brew "jq"

# Handy way to save and run project-specific commands
brew "just"

# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"

# Interpreted, interactive, object-oriented programming language
brew "python@3.8"

# Library that provides automatic proxy configuration management
brew "libproxy"

# Library for USB device access
brew "libusb"

# Next-gen compiler infrastructure
brew "llvm"

# Small build system for use with gyp or CMake
brew "ninja"

# Fast and user friendly build system
brew "meson"

# MIT/GNU Scheme development tools and runtime library
brew "mit-scheme"

# Open source relational database management system
brew "mysql"

# Open source relational database management system
brew "mysql@5.7"

# Netwide Assembler (NASM) is an 80x86 assembler
brew "nasm"

# Fast, highly customisable system info script
brew "neofetch"

# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"

# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx", restart_service: true

# Statically typed compiled systems programming language
brew "nim"

# Platform built on V8 to build network applications
brew "node", link: false

# OCaml package manager
brew "opam"

# Development kit for the Java programming language
brew "openjdk"

# Formatter for Haskell source code
brew "ormolu"

# Swiss-army knife of markup format conversion
brew "pandoc"

# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"

# Object-relational database system
brew "postgresql", restart_service: true

# Object-relational database system
brew "postgresql@12", restart_service: true

# Linter for prose
brew "proselint"

# Tools and libraries to manipulate images in many formats
brew "imagemagick"

# Static type checker for Python
brew "pyright"

# Cross-platform application and UI framework
brew "qt"

# Software environment for statistical computing
brew "r"

# Persistent key-value database, with built-in net interface
brew "redis", restart_service: true

# Search tool like grep and The Silver Searcher
brew "ripgrep"

# Readline wrapper: adds readline support to tools that lack it
brew "rlwrap"

# Utility that provides fast incremental file transfer
brew "rsync"

# Powerful, clean, object-oriented scripting language
brew "ruby"

# Experimental Rust compiler front-end for IDEs
brew "rust-analyzer"

# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"

# Autoformat shell script source code
brew "shfmt"

# Tool to create intelligent and beautiful documentation
brew "sphinx-doc"

# Cross-shell prompt for astronauts
brew "starship"

# Modernized, complete, self-contained TeX/LaTeX engine
brew "tectonic"

# User interface to the TELNET protocol
brew "telnet"

# Programmatically correct mistyped console commands
brew "thefuck"

# Terminal multiplexer
brew "tmux"

# Display directories as trees (with optional color/HTML output)
brew "tree"

# Maintained ctags implementation
brew "universal-ctags"

# Google's JavaScript engine
brew "v8"

# Vi 'workalike' with many additional features
brew "vim"

# Internet file retriever
brew "wget"

# Show the current WiFi network password
brew "wifi-password"

# Allow GNU Readline to be used with arbitrary programs
brew "with-readline"

# JavaScript package manager
brew "yarn"

# Everything you need to get started with Heroku
brew "heroku/brew/heroku"

# Simple hotkey-daemon for macOS.
brew "koekeishiya/formulae/skhd"

# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"

# High-performance, schema-free, document-oriented database
brew "mongodb/brew/mongodb-community"

# An interactive JavaScript command-line interface to MongoDB
brew "mongodb/brew/mongodb-community-shell", link: false

# Static checker for GitHub Actions workflow files
brew "rhysd/actionlint/actionlint"

# Tools and libraries to manipulate images in many formats (X11 support)
brew "tlk/imagemagick-x11/imagemagick"

brew "yudai/gotty/gotty"

brew "zegervdv/zathura/zathura"

brew "zegervdv/zathura/zathura-pdf-poppler"

# Application launcher and productivity software
cask "alfred"

cask "android-sdk"

# Memory training application
cask "anki"

# Compact TeX distribution as alternative to the full TeX Live / MacTeX
cask "basictex"

# Virtual Audio Driver
cask "blackhole-2ch"

# E-books management software
cask "calibre"

# Browser for SQLite databases
cask "db-browser-for-sqlite"

# App to build and share containerized applications and microservices
cask "docker"

# Developer platform
cask "dotnet-sdk"

# Matrix collaboration client
cask "element"

cask "font-caskaydia-cove-nerd-font"

cask "font-fira-code"

# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"

# Interface for reading and syncing eBooks
cask "kindle"

# Explore and manipulate your MongoDB data
cask "mongodb-compass"

# Free and open-source RSS reader
cask "netnewswire"

# App to write, plan, collaborate, and get organized
cask "notion"

# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"

# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"

# Development environment
cask "vagrant"

# Virtualizer for x86 hardware
cask "virtualbox"

# Open-source code editor
cask "visual-studio-code"

# Open-source version of the X.Org X Window System
cask "xquartz"
