tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "michaeleisel/zld"
tap "mongodb/brew"
tap "oven-sh/bun"
tap "terror/tap"
tap "tlk/imagemagick-x11"

# Run your GitHub Actions locally
brew "act"

# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"

# Static checker for GitHub Actions workflow files
brew "actionlint"

# Core application library for C
brew "glib"

# Zstandard is a real-time compression algorithm
brew "zstd"

# OpenType text shaping engine
brew "harfbuzz"

# Framework for layout and rendering of i18n text
brew "pango"

# Icons for the GNOME project
brew "adwaita-icon-theme"

# Development kit for the Java programming language
brew "openjdk"

# Library for command-line editing
brew "readline"

# Java build tool
brew "ant"

# Record and share terminal sessions
brew "asciinema"

# Code searching, linting, rewriting
brew "ast-grep"

# Tool for generating GNU Standards-compliant Makefiles
brew "automake"

# Open-source, cross-platform JavaScript runtime environment
brew "node"

# AWS Cloud Development Kit - framework for defining AWS infra as code
brew "aws-cdk"

# Official Amazon AWS command-line interface
brew "awscli"

# Microsoft Azure CLI 2.0
brew "azure-cli"

# Bourne-Again SHell, a UNIX command interpreter
brew "bash"

# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"

# Asynchronous event library
brew "libevent"

# Decentralized, peer to peer payment network
brew "bitcoin"

# Collection of portable C++ source libraries
brew "boost"

# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"

# Readline wrapper: adds readline support to tools that lack it
brew "rlwrap"

# Dynamic, general-purpose programming language
brew "clojure"

# Cross-platform make
brew "cmake"

# GNU File, Shell, and Text utilities
brew "coreutils"

# Cross-platform C and C++ unit testing framework for the 21st century
brew "criterion"

# Diff that understands syntax
brew "difftastic"

# Load/unload environment variables based on $PWD
brew "direnv"

# C implementation of Markdown
brew "discount"

# More intuitive version of du in rust
brew "dust"

# Generic library support script
brew "libtool"

# Functional metaprogramming aware language built on Erlang VM
brew "elixir"

# Validating, recursive, caching DNS resolver
brew "unbound"

# Incremental parsing library
brew "tree-sitter"

# GNU Emacs text editor
brew "emacs"

# LLVM bytecode to JavaScript compiler
brew "emscripten"

# Calculator REPL, similar to bc(1)
brew "eva"

# Simple, fast and user-friendly alternative to find
brew "fd"

# OCR (Optical Character Recognition) engine
brew "tesseract"

# Play, record, convert, and stream audio and video
brew "ffmpeg"

# Banner-like program prints strings as ASCII art
brew "figlet"

# Command-line tools for fly.io services
brew "flyctl"

# Command-line fuzzy finder written in Go
brew "fzf"

# GNU awk utility
brew "gawk"

# GNU compiler collection
brew "gcc"

# Interact with Google Gemini AI models from the command-line
brew "gemini-cli"

# GitHub command-line tool
brew "gh"

# Distributed revision control system
brew "git"

# Highly customizable changelog generator
brew "git-cliff"

# Enable transparent encryption/decryption of files in a git repo
brew "git-crypt"

# Syntax-highlighting pager for git and diff output
brew "git-delta"

# Statically typed language for the Erlang VM
brew "gleam"

# Library for USB device access
brew "libusb"

# GNU Pretty Good Privacy (PGP) package
brew "gnupg"

# Powerful, lightweight programming language
brew "lua"

# Cross-platform application and UI framework
brew "qt"

# Command-driven, interactive function plotting
brew "gnuplot"

# Open source programming language to build simple/reliable/efficient software
brew "go"

# Package compiler and linker metadata toolkit
brew "pkgconf"

# Generate introspection data for GObject libraries
brew "gobject-introspection"

# Fast linters runner for Go
brew "golangci-lint"

# Golang formatter that fixes long lines
brew "golines"

# Reformats Java source code to comply with Google Java Style
brew "google-java-format"

# Deliver Go binaries as fast and easily as possible
brew "goreleaser"

# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"

# Graph visualization software from AT&T and Bell Labs
brew "graphviz"

# GSettings schemas for desktop components
brew "gsettings-desktop-schemas"

# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"

# Integration point for ghcide and haskell-ide-engine. One IDE to rule them all
brew "haskell-language-server"

# Git hook and pre-commit lint manager
brew "hk"

# Haskell source code suggestions
brew "hlint"

# Improved top (interactive process viewer)
brew "htop"

# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"

# Configurable static site generator
brew "hugo"

# Command-line benchmarking tool
brew "hyperfine"

# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"

# Tools and libraries to manipulate images in many formats
brew "imagemagick"

# Dynamic language and bytecode vm
brew "janet"

# Lightweight and flexible command-line JSON processor
brew "jq"

# Handy way to save and run project-specific commands
brew "just"

# Add indentation to LaTeX files
brew "latexindent"

# Graphical front-end for GCC's coverage testing tool (gcov)
brew "lcov"

# Library that provides automatic proxy configuration management
brew "libproxy"

# XML security library
brew "libxmlsec1"

# Linux virtual machines
brew "lima"

# CLI for the Linode API
brew "linode-cli"

# Next-gen compiler infrastructure
brew "llvm"

# Next-gen compiler infrastructure
brew "llvm@18"

# Language Server for the Lua language
brew "lua-language-server"

# Java-based project management
brew "maven"

# Small build system for use with gyp or CMake
brew "ninja"

# Fast and user friendly build system
brew "meson"

# Scala language server
brew "metals"

# Polyglot runtime manager (asdf rust clone)
brew "mise"

# MIT/GNU Scheme development tools and runtime library
brew "mit-scheme"

# Open source relational database management system
brew "mysql"

# Open source relational database management system
brew "mysql@5.7"

# Netwide Assembler (NASM) is an 80x86 assembler
brew "nasm"

# Fast, highly customisable system info script
brew "neofetch"

# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"

# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"

# RSS reader for the terminal
brew "nom"

# Command-line Git information tool
brew "onefetch"

# Utility that provides fast incremental file transfer
brew "rsync"

# OCaml package manager
brew "opam"

# Formatter for Haskell source code
brew "ormolu"

# Swiss-army knife of markup format conversion
brew "pandoc"

# Port of pdftk in java
brew "pdftk-java"

# Fast, disk space efficient package manager
brew "pnpm"

# Python package management tool
brew "poetry"

# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"

# Object-relational database system
brew "postgresql@12"

# Object-relational database system
brew "postgresql@14"

# Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
brew "prettier"

# Linter for prose
brew "proselint"

# Fast static code analyzer & language server for Python
brew "pylyzer"

# Static type checker for Python
brew "pyright"

# Generic machine emulator and virtualizer
brew "qemu"

# Software environment for statistical computing
brew "r"

# Develop and deploy code with zero configuration
brew "railway"

# Persistent key-value database, with built-in net interface
brew "redis"

# Search tool like grep and The Silver Searcher
brew "ripgrep"

# Powerful, clean, object-oriented scripting language
brew "ruby"

# Extremely fast Python linter, written in Rust
brew "ruff"

# Build tool for Scala projects
brew "sbt"

# JVM-based programming language
brew "scala"

# Rich git commit graph in your terminal
brew "serie"

# Autoformat shell script source code
brew "shfmt"

# Tool to create intelligent and beautiful documentation
brew "sphinx-doc"

# Terminal-based client for Spotify
brew "spotify-tui"

# Command-line utility for SQLx, the Rust SQL toolkit
brew "sqlx-cli"

# Cross-shell prompt for astronauts
brew "starship"

# Opinionated Lua code formatter
brew "stylua"

# User interface to the TELNET protocol
brew "telnet"

# Programmatically correct mistyped console commands
brew "thefuck"

# Terminal multiplexer
brew "tmux"

# Program that allows you to count code, quickly
brew "tokei"

# Display directories as trees (with optional color/HTML output)
brew "tree"

# Language Server Protocol implementation for TypeScript wrapping tsserver
brew "typescript-language-server", link: false

# Markup-based typesetting system
brew "typst"

# Beautiful and reliable typst code formatter
brew "typstyle"

# Maintained ctags implementation
brew "universal-ctags"

# Extremely fast Python package installer and resolver, written in Rust
brew "uv"

# Google's JavaScript engine
brew "v8"

# Executes a program periodically, showing output fullscreen
brew "watch"

# Watch files and take action when they change
brew "watchman"

# Internet file retriever
brew "wget"

# Show the current WiFi network password
brew "wifi-password"

# Allow GNU Readline to be used with arbitrary programs
brew "with-readline"

# Formatter for python code
brew "yapf", link: false

# JavaScript package manager
brew "yarn"

# Programming language designed for robustness, optimality, and clarity
brew "zig"

# Shell extension to navigate your filesystem faster
brew "zoxide"

# Everything you need to get started with Heroku
brew "heroku/brew/heroku"

# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"

# High-performance, schema-free, document-oriented database
brew "mongodb/brew/mongodb-community"

# An interactive JavaScript command-line interface to MongoDB
brew "mongodb/brew/mongodb-community-shell"

# Incredibly fast JavaScript runtime, bundler, transpiler and package manager - all in one.
brew "oven-sh/bun/bun"

# Bulk rename files using your favorite editor
brew "terror/tap/edmv"

# Language server for just
brew "terror/tap/just-lsp"

# Interpolate shell command output directly into markdown
brew "terror/tap/present"

# Centralized view for all of your tmux panes
brew "terror/tap/spymux"

# Arbitrary precision calculator language
brew "terror/tap/val"

# Command-line interface for 1Password
cask "1password-cli"

# Password manager
cask "1password@nightly"

# GPU-accelerated terminal emulator
cask "alacritty"

# Chromium based browser
cask "arc"

# Compact TeX distribution as alternative to the full TeX Live / MacTeX
cask "basictex"

# Virtual Audio Driver
cask "blackhole-2ch"

# Automated testing of webapps for Google Chrome
cask "chromedriver"

# Anthropic's official Claude AI desktop app
cask "claude"

# Tool to remove unnecessary files and folders from disk
cask "cleanmymac"

# OpenAI's coding agent that runs in your terminal
cask "codex"

# Write, edit, and chat about your code with AI
cask "cursor"

# Command-line agent for Cursor
cask "cursor-cli"

# Voice and text chat software
cask "discord"

# Client for the Dropbox cloud storage service
cask "dropbox"
cask "font-caskaydia-cove-nerd-font"
cask "font-fira-code"
cask "font-fontawesome"
cask "font-inter"

# Web browser
cask "google-chrome"

# GraalVM from Oracle
cask "graalvm-jdk"

# Dedicated scratchpad for developers
cask "heynote"

# Interface for reading and syncing eBooks
cask "kindle"

# Provides updates to various Microsoft products
cask "microsoft-auto-update"

# Spreadsheet software
cask "microsoft-excel"

# VPN client
cask "mullvad-vpn"

# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"

# Open-source software for live streaming and screen recording
cask "obs"

# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"

# Replacement for Docker Desktop
cask "orbstack"

# All-in-one bookmark manager
cask "raindropio"

# Control your tools with a few keystrokes
cask "raycast"

# Save articles to read, highlight key content, and organise notes for review
cask "reader"

# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"

# Block your own access to distracting websites
cask "selfcontrol"

# Tool for sending personal documents to Kindles from Macs
cask "send-to-kindle"

# Instant messaging application focusing on security
cask "signal"

# Team communication and collaboration software
cask "slack"

# Bitcoin wallet application
cask "sparrow"

# Music streaming service
cask "spotify"

# Web browser focusing on security
cask "tor-browser"

# Development environment
cask "vagrant"

# Open-source code editor
cask "visual-studio-code"

# Multiplayer code editor
cask "zed"
vscode "rust-lang.rust-analyzer"
vscode "vscodevim.vim"
go "github.com/google/pprof"
