- defaults:
    link:
      relink: true

- clean:
  - '~'
  - '~/.cargo'
  - '~/.config'

- link:
  ~/.aliases: etc/bash/aliases
  ~/.bash_profile: etc/bash/bash_profile
  ~/.bashrc: etc/bash/bashrc
  ~/.bin: bin
  ~/.config: etc
  ~/.functions: etc/bash/functions
  ~/.gitconfig: etc/gitconfig
  ~/.hushlogin: config/hushlogin
  ~/.submodules: submodules
  ~/.tmux.conf: etc/tmux.conf
  ~/.vim: etc/vim
  ~/.vimrc: etc/vimrc
  ~/.vscode: etc/vscode

- shell:
  - [git submodule update --init --recursive, Installing submodules]
