- defaults:
    link:
      relink: true

- clean: ['~']

- link:
  ~/.Brewfile: brew/Brewfile
  ~/.aliases: .aliases
  ~/.bash_profile: .bash_profile
  ~/.bashrc: .bashrc
  ~/.bin: bin
  ~/.config: config
  ~/.functions: .functions
  ~/.gitconfig: git/gitconfig
  ~/.hooks: hooks
  ~/.hushlogin: config/hushlogin
  ~/.submodules: submodules
  ~/.vim: vim
  ~/.vimrc: .vimrc
  ~/.vscode: vscode

- shell:
  - [git submodule update --init --recursive, Installing submodules]
