- clean:
  - '~'
  - ~/.cargo
  - ~/.config

- create:
  - ~/.cargo
  - ~/.codex
  - ~/.config/alacritty
  - ~/.config/git
  - ~/.config/neofetch
  - ~/src
  - ~/tmp

- link:
    ~/.aliases: etc/bash/aliases
    ~/.bash_profile: etc/bash/bash_profile
    ~/.bashrc: etc/bash/bashrc
    ~/.bin: bin
    ~/.bp: etc/bp
    ~/.brewfile: brew/Brewfile
    ~/.claude/CLAUDE.md: etc/agents.md
    ~/.codex/AGENTS.md: etc/agents.md
    ~/.codex/config.toml: etc/codex/config.toml
    ~/.config/alacritty/alacritty.toml: etc/alacritty.toml
    ~/.config/gitconfig: etc/gitconfig
    ~/.config/htoprc: etc/htoprc
    ~/.config/mise: etc/mise
    ~/.config/neofetch/config.conf: etc/neofetch/config.conf
    ~/.config/nvim: etc/nvim
    ~/.config/starship.toml: etc/starship.toml
    ~/.functions: etc/bash/functions
    ~/.gitconfig: etc/gitconfig
    ~/.gitignore.global: etc/gitignore.global
    ~/.haxornewsconfig: etc/haxornewsconfig
    ~/.hushlogin: etc/hushlogin
    ~/.macos: etc/macos
    ~/.npmrc: etc/npmrc
    ~/.pi/agents/AGENTS.md: etc/agents.md
    ~/.ripgreprc: etc/ripgreprc
    ~/.skeleton: etc/skeleton
    ~/.skhdrc: etc/skhdrc
    ~/.submodules: submodules
    ~/.tmux.conf: etc/tmux.conf
    ~/.vim: etc/vim
    ~/.vimrc: etc/vimrc
    ~/.vscode: etc/vscode
    ~/.yabairc: etc/yabairc
    ~/.zsh: etc/zsh
    ~/.zshrc: etc/zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  - brew install just
  - just all
