export GOPATH="$HOME/.go"
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/Desktop/contest-cli:$PATH"
export PATH="$HOME/Desktop/kattis-cli:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
export PATH="/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/sbin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/sbin:$PATH"
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

if [ -f "$HOME"/.bashrc ]; then
  source "$HOME"/.bashrc
fi
