#!/usr/bin/env bash

export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
export PATH="/bin:$PATH"
export PATH="/opt/homebrew/Cellar/llvm@18/18.1.8/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/sbin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/sbin:$PATH"

if [ -f "$HOME"/.bashrc ]; then
  source "$HOME"/.bashrc
fi
