require 'util'

local home    = vim.env.HOME
local config  = home .. '/.config/nvim'

map('i', '!',                                         '!<c-g>u')
map('i', ',',                                         ',<c-g>u')
map('i', '.',                                         '.<c-g>u')
map('i', '<down>',                                      '<nop>')
map('i', '<left>',                                      '<nop>')
map('i', '<right>',                                     '<nop>')
map('i', '<up>',                                        '<nop>')
map('i', '?',                                         '?<c-g>u')
map('n', '0',                                               '^')
map('n', '<c-j>',                                     ':bp<cr>')
map('n', '<c-k>',                                     ':bn<cr>')
map('n', '<c-l>',                 ':noh<cr>', { silent = true })
map('n', '<c-s>',               '<cmd>Telescope find_files<cr>')
map('n', '<down>',                                      '<nop>')
map('n', '<leader>ad',                         ':ALEDetail<cr>')
map('n', '<leader>ea',                  ':split ~/.aliases<cr>')
map('n', '<leader>en',                        ':e notes.md<cr>')
map('n', '<leader>sa',           '<cmd>Telescope live_grep<cr>')
map('n', '<leader>sb',             '<cmd>Telescope buffers<cr>')
map('n', '<leader>ss',                          ':source %<cr>')
map('n', '<leader>sv', ':luafile ' .. config .. '/init.lua<cr>')
map('n', '<left>',                                      '<nop>')
map('n', '<right>',                                     '<nop>')
map('n', '<up>',                                        '<nop>')
map('n', 'Y',                                              'y$')
map('n', 'Z',                                     '<cmd>wq<cr>')
map('n', '^',                                               '0')
map('o', 'b',                                              'i[')
map('o', 'p',                                              'i(')
map('v', '<leader>a"',                     ':Tabularize /"<cr>')
map('v', '<leader>a#',                     ':Tabularize /#<cr>')
map('v', '<leader>a:',                     ':Tabularize /:<cr>')
map('v', '<leader>a=',                     ':Tabularize /=<cr>')
map('v', '<leader>s',                               ':sort<cr>')
