require 'util'

map('i', '<down>',                        '<nop>')
map('i', '<left>',                        '<nop>')
map('i', '<right>',                       '<nop>')
map('i', '<up>',                          '<nop>')
map('n', '0',                                 '^')
map('n', '<c-s>', '<cmd>Telescope find_files<cr>')
map('n', '<down>',                        '<nop>')
map('n', '<leader>ss',            ':source %<cr>')
map('n', '<left>',                        '<nop>')
map('n', '<right>',                       '<nop>')
map('n', '<up>',                          '<nop>')
map('n', 'Z',                       '<cmd>wq<cr>')
map('n', '^',                                 '0')
map('o', 'b',                                'i[')
map('o', 'p',                                'i(')
map('v', '<leader>a"',       ':Tabularize /"<cr>')
map('v', '<leader>a#',       ':Tabularize /#<cr>')
map('v', '<leader>a:',       ':Tabularize /:<cr>')
map('v', '<leader>a=',       ':Tabularize /=<cr>')
map('v', '<leader>s',                 ':sort<cr>')
