add_newline = false
format      = "$username$directory$git_branch"

[username]
format      = "[$user]($style) :: "
style_user  = "bold cyan"
show_always = true

[directory]
style = "bold yellow"

[character]
symbol        = "$"
style_failure = "bold green"

[git_branch]
format = "-> [$symbol$branch]($style) "
symbol = ""
style  = "bold green"
