alias -- -="z -"
alias: .. 'z ..'
alias: ... 'z ../..'
alias: .... 'z ../../..'
alias: ..... 'z ../../../..'
alias: arc 'open /Applications/Arc.app'
alias: cb 'git branch --show-current'
alias: cd 'z'
alias: d 'z ~/dotfiles'
alias: dc 'docker-compose up -d'
alias: e 'exit'
alias: evrc 'nvim ~/dotfiles/etc/nvim'
alias: fcd 'z "$(fd --type directory | fzf)"'
alias: g 'git'
alias: ga 'git add'
alias: gap 'git add -p'
alias: gb 'git branch'
alias: gbd 'git branch --delete'
alias: gc 'git commit'
alias: gca 'git commit --amend --no-edit'
alias: gcb 'git checkout -b'
alias: gch 'git checkout'
alias: gd 'git diff'
alias: gp 'git push -u origin master'
alias: gpf 'git push -f origin master'
alias: gpo 'git push origin'
alias: gst 'git status'
alias: i 'zi'
alias: j 'just'
alias: l 'ls'
alias: la 'ls -a'
alias: ll 'ls -lah'
alias: lt 'tree -L 1'
alias: lv 'nvim -c "normal '\''0" -c bd1'
alias: m 'tmux'
alias: n 'notes'
alias: daily 'notes daily'
alias: ns 'notes search'
alias: ov 'vim'
alias: pcb 'git push origin "$(git branch --show-current)"'
alias: pr 'gh pr create --web'
alias: reload 'exec ${SHELL} -l'
alias: sb 'source ~/.zshrc'
alias: sl 'ls'
alias: sra 'alias | fzf'
alias: trm 'tmux kill-server'
alias: v 'nvim'
alias: vi 'nvim'
alias: w 'z ~/src'
alias: wifi 'wifi-password'
alias: ~ 'z ~'
